name: Build Origin Version

on:
  push:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    strategy:
      matrix:
        jdkversion: [17]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdkversion }}
        cache: 'maven'
        
    - name: Configure Git User Details
      run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
    - name: Remove
      run: rm target/* -f
    - name: Build with Maven
      run: |
          git clone https://gitlab.com/phoenix-dvpmt/mythiclib.git core
          cd core
          mvn -V -B clean package --file pom.xml
    - name: upload
      uses: actions/upload-artifact@v3
      with:
       name: MythicLib
       path: core/target
    - name: automatic releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         automatic_release_tag: "latest"
         prerelease: false
         title: "MythicLib 自动构建最新版本"
         files: |
           core/target/*.jar
